name: API testing

on:
  workflow_dispatch:

jobs:
  api-tests:
    name: Run API Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '19'

      - name: Debug API Connectivity
        run: |
          curl -v -H "Authorization: token ${{ secrets.GITEA_API_TOKEN }}" https://daa5-5-29-126-14.ngrok-free.app/api/v1/user/repos || true

      - name: Run API Tests
        env:
          GITEA_API_TOKEN: ${{ secrets.GITEA_API_TOKEN }}
        run: |
          mvn -X clean test -Dtest=**/apiTests/*
