name: API testing

on:
  workflow_dispatch:

jobs:
 api-tests:
    name: Run API Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Define secrets
        run: |
          echo "GITEA_API_TOKEN=${{ secrets.GITEA_API_TOKEN }}" > .env
          
      - name: Load environment variables
        run: export $(cat .env | xargs)

      - name: Debug environment
        run: |
          echo "Contents of .env:"
          cat .env
          echo "Environment variables:"
          env

      - name: Debug API Connectivity
        run: |
          curl -v -H "Authorization: token ${{ secrets.GITEA_API_TOKEN }}" https://daa5-5-29-126-14.ngrok-free.app/api/v1/user/repos || true

      - name: Run API Tests
        run: |
          mvn -q test -Dtest=**/apiTests/*
          env:
            GITEA_API_TOKEN: ${{ secrets.GITEA_API_TOKEN }}
